// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: pbf/signature/verify.proto

package signature

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VerifyI is the input for verifying signatures.
//
//	{
//	    "object": [
//	        {
//	            "public": {
//	                "mess": "It's-a me, Mario!",
//	                "pubk": "0x1234",
//	                "sign": "0x2345"
//	            }
//	        }
//	    ]
//	}
type VerifyI struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *VerifyI_Filter   `protobuf:"bytes,100,opt,name=filter,proto3" json:"filter,omitempty"`
	Object []*VerifyI_Object `protobuf:"bytes,200,rep,name=object,proto3" json:"object,omitempty"`
}

func (x *VerifyI) Reset() {
	*x = VerifyI{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyI) ProtoMessage() {}

func (x *VerifyI) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyI.ProtoReflect.Descriptor instead.
func (*VerifyI) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyI) GetFilter() *VerifyI_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *VerifyI) GetObject() []*VerifyI_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type VerifyI_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyI_Filter) Reset() {
	*x = VerifyI_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyI_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyI_Filter) ProtoMessage() {}

func (x *VerifyI_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyI_Filter.ProtoReflect.Descriptor instead.
func (*VerifyI_Filter) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{1}
}

type VerifyI_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Intern *VerifyI_Object_Intern `protobuf:"bytes,100,opt,name=intern,proto3" json:"intern,omitempty"`
	Public *VerifyI_Object_Public `protobuf:"bytes,200,opt,name=public,proto3" json:"public,omitempty"`
}

func (x *VerifyI_Object) Reset() {
	*x = VerifyI_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyI_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyI_Object) ProtoMessage() {}

func (x *VerifyI_Object) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyI_Object.ProtoReflect.Descriptor instead.
func (*VerifyI_Object) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyI_Object) GetIntern() *VerifyI_Object_Intern {
	if x != nil {
		return x.Intern
	}
	return nil
}

func (x *VerifyI_Object) GetPublic() *VerifyI_Object_Public {
	if x != nil {
		return x.Public
	}
	return nil
}

type VerifyI_Object_Intern struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyI_Object_Intern) Reset() {
	*x = VerifyI_Object_Intern{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyI_Object_Intern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyI_Object_Intern) ProtoMessage() {}

func (x *VerifyI_Object_Intern) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyI_Object_Intern.ProtoReflect.Descriptor instead.
func (*VerifyI_Object_Intern) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{3}
}

type VerifyI_Object_Public struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// mess is the message to sign.
	Mess string `protobuf:"bytes,100,opt,name=mess,proto3" json:"mess,omitempty"`
	// pubk is the hex encoded compressed public key expected to be recovered from
	// the given signature.
	Pubk string `protobuf:"bytes,200,opt,name=pubk,proto3" json:"pubk,omitempty"`
	// sign is the signature of the given message.
	Sign string `protobuf:"bytes,300,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *VerifyI_Object_Public) Reset() {
	*x = VerifyI_Object_Public{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyI_Object_Public) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyI_Object_Public) ProtoMessage() {}

func (x *VerifyI_Object_Public) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyI_Object_Public.ProtoReflect.Descriptor instead.
func (*VerifyI_Object_Public) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyI_Object_Public) GetMess() string {
	if x != nil {
		return x.Mess
	}
	return ""
}

func (x *VerifyI_Object_Public) GetPubk() string {
	if x != nil {
		return x.Pubk
	}
	return ""
}

func (x *VerifyI_Object_Public) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

// VerifyO is the output for verifying signatures.
//
//	{
//	    "object": [
//	        {
//	            "intern": {
//	                "stts": "verified"
//	            }
//	        }
//	    ]
//	}
type VerifyO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *VerifyO_Filter   `protobuf:"bytes,100,opt,name=filter,proto3" json:"filter,omitempty"`
	Object []*VerifyO_Object `protobuf:"bytes,200,rep,name=object,proto3" json:"object,omitempty"`
}

func (x *VerifyO) Reset() {
	*x = VerifyO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyO) ProtoMessage() {}

func (x *VerifyO) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyO.ProtoReflect.Descriptor instead.
func (*VerifyO) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyO) GetFilter() *VerifyO_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *VerifyO) GetObject() []*VerifyO_Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type VerifyO_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyO_Filter) Reset() {
	*x = VerifyO_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyO_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyO_Filter) ProtoMessage() {}

func (x *VerifyO_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyO_Filter.ProtoReflect.Descriptor instead.
func (*VerifyO_Filter) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{6}
}

type VerifyO_Object struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Intern *VerifyO_Object_Intern `protobuf:"bytes,100,opt,name=intern,proto3" json:"intern,omitempty"`
	Public *VerifyO_Object_Public `protobuf:"bytes,200,opt,name=public,proto3" json:"public,omitempty"`
}

func (x *VerifyO_Object) Reset() {
	*x = VerifyO_Object{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyO_Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyO_Object) ProtoMessage() {}

func (x *VerifyO_Object) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyO_Object.ProtoReflect.Descriptor instead.
func (*VerifyO_Object) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyO_Object) GetIntern() *VerifyO_Object_Intern {
	if x != nil {
		return x.Intern
	}
	return nil
}

func (x *VerifyO_Object) GetPublic() *VerifyO_Object_Public {
	if x != nil {
		return x.Public
	}
	return nil
}

type VerifyO_Object_Intern struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// stts is the resource status upon successful signature verification.
	Stts string `protobuf:"bytes,100,opt,name=stts,proto3" json:"stts,omitempty"`
}

func (x *VerifyO_Object_Intern) Reset() {
	*x = VerifyO_Object_Intern{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyO_Object_Intern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyO_Object_Intern) ProtoMessage() {}

func (x *VerifyO_Object_Intern) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyO_Object_Intern.ProtoReflect.Descriptor instead.
func (*VerifyO_Object_Intern) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyO_Object_Intern) GetStts() string {
	if x != nil {
		return x.Stts
	}
	return ""
}

type VerifyO_Object_Public struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyO_Object_Public) Reset() {
	*x = VerifyO_Object_Public{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbf_signature_verify_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyO_Object_Public) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyO_Object_Public) ProtoMessage() {}

func (x *VerifyO_Object_Public) ProtoReflect() protoreflect.Message {
	mi := &file_pbf_signature_verify_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyO_Object_Public.ProtoReflect.Descriptor instead.
func (*VerifyO_Object_Public) Descriptor() ([]byte, []int) {
	return file_pbf_signature_verify_proto_rawDescGZIP(), []int{9}
}

var File_pbf_signature_verify_proto protoreflect.FileDescriptor

var file_pbf_signature_verify_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x62, 0x66, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x70, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x49, 0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x64, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0xc8, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x49, 0x5f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x85, 0x01, 0x0a, 0x0e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x38,
	0x0a, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x49, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x52, 0x06, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x06, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x22, 0x17, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x22, 0x55, 0x0a, 0x15,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x73, 0x73, 0x18, 0x64, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x73, 0x73, 0x12, 0x13, 0x0a, 0x04, 0x70, 0x75, 0x62,
	0x6b, 0x18, 0xc8, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x75, 0x62, 0x6b, 0x12, 0x13,
	0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0xac, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x69, 0x67, 0x6e, 0x22, 0x70, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x12, 0x31,
	0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x4f, 0x5f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x32, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0xc8, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f,
	0x5f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x85, 0x01, 0x0a, 0x0e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x4f, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x18, 0x64, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x5f, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x52, 0x06, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x12, 0x39, 0x0a, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0xc8,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x5f, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22,
	0x2b, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x74, 0x73,
	0x18, 0x64, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x74, 0x74, 0x73, 0x22, 0x17, 0x0a, 0x15,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x5f, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x3b, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbf_signature_verify_proto_rawDescOnce sync.Once
	file_pbf_signature_verify_proto_rawDescData = file_pbf_signature_verify_proto_rawDesc
)

func file_pbf_signature_verify_proto_rawDescGZIP() []byte {
	file_pbf_signature_verify_proto_rawDescOnce.Do(func() {
		file_pbf_signature_verify_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbf_signature_verify_proto_rawDescData)
	})
	return file_pbf_signature_verify_proto_rawDescData
}

var file_pbf_signature_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pbf_signature_verify_proto_goTypes = []interface{}{
	(*VerifyI)(nil),               // 0: signature.VerifyI
	(*VerifyI_Filter)(nil),        // 1: signature.VerifyI_Filter
	(*VerifyI_Object)(nil),        // 2: signature.VerifyI_Object
	(*VerifyI_Object_Intern)(nil), // 3: signature.VerifyI_Object_Intern
	(*VerifyI_Object_Public)(nil), // 4: signature.VerifyI_Object_Public
	(*VerifyO)(nil),               // 5: signature.VerifyO
	(*VerifyO_Filter)(nil),        // 6: signature.VerifyO_Filter
	(*VerifyO_Object)(nil),        // 7: signature.VerifyO_Object
	(*VerifyO_Object_Intern)(nil), // 8: signature.VerifyO_Object_Intern
	(*VerifyO_Object_Public)(nil), // 9: signature.VerifyO_Object_Public
}
var file_pbf_signature_verify_proto_depIdxs = []int32{
	1, // 0: signature.VerifyI.filter:type_name -> signature.VerifyI_Filter
	2, // 1: signature.VerifyI.object:type_name -> signature.VerifyI_Object
	3, // 2: signature.VerifyI_Object.intern:type_name -> signature.VerifyI_Object_Intern
	4, // 3: signature.VerifyI_Object.public:type_name -> signature.VerifyI_Object_Public
	6, // 4: signature.VerifyO.filter:type_name -> signature.VerifyO_Filter
	7, // 5: signature.VerifyO.object:type_name -> signature.VerifyO_Object
	8, // 6: signature.VerifyO_Object.intern:type_name -> signature.VerifyO_Object_Intern
	9, // 7: signature.VerifyO_Object.public:type_name -> signature.VerifyO_Object_Public
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_pbf_signature_verify_proto_init() }
func file_pbf_signature_verify_proto_init() {
	if File_pbf_signature_verify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbf_signature_verify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyI); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyI_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyI_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyI_Object_Intern); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyI_Object_Public); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyO_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyO_Object); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyO_Object_Intern); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbf_signature_verify_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyO_Object_Public); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbf_signature_verify_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbf_signature_verify_proto_goTypes,
		DependencyIndexes: file_pbf_signature_verify_proto_depIdxs,
		MessageInfos:      file_pbf_signature_verify_proto_msgTypes,
	}.Build()
	File_pbf_signature_verify_proto = out.File
	file_pbf_signature_verify_proto_rawDesc = nil
	file_pbf_signature_verify_proto_goTypes = nil
	file_pbf_signature_verify_proto_depIdxs = nil
}
